Added additional check in withCookieHeader.
guzzle/guzzle pull request #2405
Opened 2019-11-19 21:49 UTC by Miljan9602

Added check for Host header. If check does not match domain from uri, cookie will not be added.

2019-12-08 18:32 UTC, Nyholm commented on composer.json
> +    "name": "miljan9602/guzzle",
Oh, please dont rename the package =)

2019-12-08 18:40 UTC, nemanjan00 commented
We have no idea how exacly we would test for something like this. 

Problem happens when we want to send request to different reverse proxy, on purpose. 

We change address to `http://reverseproxyaddress/` and add header `Host: originalolaction` and, cookies for `reverseproxyaddress` are used, instead of those for `originallocation`

2019-12-29 18:07 UTC, GrahamCampbell commented
I don't understand the use case here. Why would a cookie for a different domain be added?

2020-01-02 21:12 UTC, nemanjan00 commented
In some test cases, we want to pick specific reverse rpoxy instance. 

If we specify that reverse proxy in host, we need to specify Domain header, so reverse proxy knows what domain we are requesting, and, we also want to use cookies for that domain.

2020-09-22 18:29 UTC, Nyholm commented
Friendly ping

2020-09-22 22:19 UTC, GrahamCampbell commented
This is also missing tests.,

2020-10-01 20:32 UTC, GrahamCampbell requested changes

2020-10-01 20:32 UTC, GrahamCampbell commented on src/Cookie/CookieJar.php
> +        if (sizeof($request->getHeader('Host')) > 0) {
When can there be no Host header?

2021-02-12 21:45 UTC, closed without merging