Robust handling of responses with invalid headers
guzzle/guzzle pull request #2872
Opened 2021-03-13 21:26 UTC by GrahamCampbell

Thanks to @TimWolla for raising the issue.

2021-03-13 21:31 UTC, TimWolla approved these changes

2021-03-21 16:36 UTC, Nyholm requested changes
I did a quick look. 

I think this is alright. 
Well done

2021-03-21 16:36 UTC, Nyholm commented on src/Handler/HeaderProcessor.php
> +    public static function parseHeaders(array $hdrs): array
Let's use `$headers`

2021-03-21 16:36 UTC, Nyholm commented on src/Handler/HeaderProcessor.php
> +        $ver = \explode('/', $parts[0])[1] ?? null;
We can also afford to call this variable `$version`

2021-03-21 16:36 UTC, Nyholm commented on src/Handler/StreamHandler.php
> +            $msg = 'An error was encountered while creating the response';
This variable is not really needed.

2021-03-21 17:40 UTC, Nyholm approved these changes
Thank you

2021-03-21 17:40 UTC, merged